### PR TITLE
restore creation legacy wallet at 26 ver

### PR DESCRIPTION
**Pull request by mraksoll4**
Restore creation legacy wallet at 26 ver

This is temp sollution before implementation suppoer description wallet.

### CODE REVIEW

**Comment by bitcoin-pow** [comment]
Why does the community need this update? The goal is to keep current with the latest BTC code, not go back in time.

**Comment by mraksoll4** [comment]
this restore creation of legacy wallet.dat , what support POS logic via 

```
    LegacyScriptPubKeyMan* spk_man = GetLegacyScriptPubKeyMan();
    if (!spk_man)
    {
        LogPrint(BCLog::COINSTAKE, "CreateCoinStake : failed to get signing provider\n");
        return false;
    }
```

pos logic not support sing from descriptor wallet if you create fresh wallet.dat.

even at address start at 1 you get CreateCoinStake : failed to get signing provider


so temp solution allow users to create legacy wallet , or 26 wallet now simple not usable for new users, they cannot mine at it.


explain  if you create new wallet at version 26 - you default create descriptor wallet , and there no matter what address type you use , it working over descriptor sing logic so at debug=1 you get CreateCoinStake : failed to get signing provider

now solution create wallet at 21 and put wallet.dat to folder 26 , and not touch migration.

this simple allow users to use it as is before solution for desctriptor will be found ( at process)

**Comment by mraksoll4** [comment]
create at new 26 wallet - new wallet , there will be no choice create non descrptor wallet.

then create legacy addreses and try send to them any amount.

when you start mining you will always get CreateCoinStake : failed to get signing provider
due using GetLegacyScriptPubKeyMan()

this fix restore menu to create non descriptor what don't have any problem at 26 or 27 ( tested also ) or 26 wallet simple not usable for mining if you create wallet at it.

**Comment by bitcoin-pow** [comment]
Thanks for the info. This is a great find. We have opened a new feature request and gave you credit.
Please push the code updates to the following branch:

https://github.com/bitcoin-pow/BitcoinPoW/issues/38

https://github.com/bitcoin-pow/BitcoinPoW/tree/38-restore-creation-legacy-wallet-at-26-ver

**Comment by bitcoin-pow** [comment]
https://github.com/bitcoin-pow/BitcoinPoW/tree/38-restore-creation-legacy-wallet-at-26-ver

**Pull request closed without merging**
